version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - proxy
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - proxy
      - database
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - containerdb:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - database

volumes:
  wordpress_files:

  containerdb:

networks:
  proxy:

  database:
    driver: bridge
