version: '3'

services:
  nginx:
    build: ./requirements/nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - proxy
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - proxy
      - database
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - containerdb:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - database

volumes:
  wordpress_files:

  containerdb:

networks:
  proxy:

  database:
