version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - ~/data/wordpress_files:/var/www/html
    networks:
      - proxy
    secrets:
      - server_certificate
      - server_key
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - ~/data/wordpress_files:/var/www/html
    networks:
      - proxy
      - database
    secrets:
      - mysql_pass
      - wp_admin_pass
      - wp_user_pass
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - ~/data/mysql:/var/lib/mysql
    networks:
      - database
    secrets:
      - mysql_pass

networks:
  proxy:

  database:

secrets:
  server_certificate:
    file: ./secrets/server.nginx.pem
  server_key:
    file: ./secrets/server.key
  mysql_pass:
    file: ./secrets/db_password.txt
  wp_admin_pass:
    file: ./secrets/wp_admin_password.txt
  wp_user_pass:
    file: ./secrets/wp_user_password.txt
  
